
name: "test, lint and publish"

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: "Test (Python ${{ matrix.python-version }}, SQLAlchemy ${{ matrix.sqlalchemy-version }})"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        sqlalchemy-version: ["2.0", "2.1"]
    uses: ./.github/workflows/_test.yaml
    with:
      coverage: true
      python-version: ${{ matrix.python-version }}
      sqlalchemy-version: ${{ matrix.sqlalchemy-version }}
  lint:
    name: "Lint (Python ${{ matrix.python-version }})"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    needs: test
    uses: ./.github/workflows/_lint.yaml
    with:
      python-version: ${{ matrix.python-version }}